version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
      args:
        API_KEY: "${API_KEY}"
    image: "map-app-server-image"
    container_name: "map-app-server"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./config/database/database.db
        target: /app/database/database.db
